### ISSUE TITLE
Error: parts.at is not a function

### ISSUE THREAD

**Issue by jsem** [newrelic/newrelic-lambda-layers#101]
## Description

Looks like there is an error in the latest version of the new relic nodejs lambda layer (version 67).

All of our lambdas using the new version pushed yesterday are now seeing the error `parts.at is not a function`

## Relevant Logs / Console output

```
parts.at is not a function

at getHandler (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:32:31)
```

## Your Environment

AWS lambda using the `NewRelicNodeJS14X` layer: `arn:aws:lambda:ap-southeast-2:451483290750:layer:NewRelicNodeJS14X:67`

**Comment by daleobrien** [comment]
+1

**Comment by mrickard** [comment]
@jsem Thank you for the report. We'll investigate, but in the meantime we recommend reverting to the previous layer version for Node 14.

**Comment by mrickard** [comment]
@jsem @daleobrien Would you be able to share the values you're using for `NEW_RELIC_LAMBDA_HANDLER`?

**Comment by RomAnoX** [comment]
+1

**Comment by islas27** [comment]
Based on the code on the latest update for the Node layer at: https://github.com/newrelic/newrelic-lambda-layers/commit/3b8411996ffa66e223e9a4154b60ff04324aff7c

`Parts.at` is not supported for v14, as per Mozila's documentation `Array.prototype.at()` wasn't added to node until v16:
[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility)

**Comment by jsem** [comment]
@mrickard we've reverted to version `66` and it's working. The values we use for `NEW_RELIC_LAMBDA_HANDLER` are `index.handler` and `index.onEvent` but looks like it's probably a node version issue rather than an input issue.

**Comment by daleobrien** [comment]
@mrickard , this is what we have

```json
{
  "NEW_RELIC_ACCOUNT_ID": "XXXXX",
  "NEW_RELIC_API_KEY": "XXXXX",
  "NEW_RELIC_REGION": "eu",
  "NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS": "true",
  "NEW_RELIC_LAMBDA_EXTENSION_ENABLED": "true",
  "NEW_RELIC_LAMBDA_HANDLER": "index.handler"
}
```

**Comment by darrensmithwtc** [comment]
Hi

We unfortunately also had this issue this morning as well for a client's live deploy.  NR Case #00059952 and had to revert to version 66 in a hurry.  Likewise our input string was fine as they are formatted; "main.funcName" i.e. "main.addToCart" so must be related to the Node V14 and Parts.at as per @islas27 's comment.

**Comment by mrickard** [comment]
A fix for this is in PR; we'll get new layers out today. Thank you all for reporting!

**Comment by mrickard** [comment]
New layers are being published now. Thank you all for reporting! (@jsem @daleobrien @RomAnoX @islas27)
