### ISSUE TITLE
[Python] Lambda layer includes GLIBC_2.28

### ISSUE THREAD

**Issue by nopjmp** [newrelic/newrelic-lambda-layers#115]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Due to a dependency that includes cryptography as a dependency, the pip install build process will package cryptography into the lambda layer. This causes a conflict if the user additionally installs the cryptography library as part of their dependencies. The CI process uses circleci/python

## Steps to Reproduce

Use latest Python lambda layer with a project that use cryptography library 38.x.

## Expected Behaviour

Lambda function should run accordingly.

## Relevant Logs / Console output

    [ERROR] Runtime.ImportModuleError: Unable to import module 'newrelic_lambda_wrapper': Failed to import module 'lambda_function': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)Traceback (most recent call last): | [ERROR] Runtime.ImportModuleError: Unable to import module 'newrelic_lambda_wrapper': Failed to import module 'lambda_function': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so) Traceback (most recent call last):

## Your Environment

AWS Lambda Python 3.8

Docker image for our Python project: public.ecr.aws/sam/build-python3.8:latest

## Additional context

We are using the smbclient library, but it's not entirely related to that library. 

circleci/python:3.8 glibc version

circleci@5c2149770425:/$ apt info libc6-dev
Package: libc6-dev
Version: 2.31-13+deb11u2

**Comment by hmstepanek** [comment]
We aren't able to find any dependency on cryptography in newrelic's code. Could the issue be in one of your dependencies that is not newrelic?

**Comment by nopjmp** [comment]
I will double check tomorrow, we had the issue at one point but we resolved it and still ran into the error message until I removed the lambda layer.

**Comment by nopjmp** [comment]
This appeared to possibly be something in our build pipeline that was hidden from me, at least in my case.
