### ISSUE TITLE
.zip file location

### ISSUE THREAD

**Issue by leslie-alldridge** [newrelic/newrelic-lambda-layers#13]
Hi team

Is it possible to include a link to, or, provide us with a .zip file so we can upload the lambda layer manually?

Thanks

**Comment by kolanos** [comment]
@leslie-alldridge Thanks for the suggestion. I transferred your issue to this repository as this is where the layers a built. I think it is a good idea to upload the layer zip files as artifacts with every release here.

**Comment by leslie-alldridge** [comment]
Wicked cheers

**Comment by chaudharysaket** [comment]
You can go over the publish scripts as discussed [here](https://layers.newrelic-external.com/). You can also utilise the build step to build the zip file that can be used to create layer manually.
