### ISSUE TITLE
Incorrect error message when dependency module is not loading

### ISSUE THREAD

**Issue by ptrap** [newrelic/newrelic-lambda-layers#130]
It looks that the error handling of this function is a bit too harsh and obfuscating the actual error message. If a dependency that is included is missing, it will report that the entrypoint is missing instead of that module.

https://github.com/newrelic/newrelic-lambda-layers/blob/d42eb2c43e38f98536e42db5e10b8f52f0315ef4/nodejs/index.js#L47

STR: 
- Make a nodejs 16 lambda which includes the aws-sdk v2 in the entrypoint file and use the new relic entrypoint
- Swap over to nodejs 18 without updating the aws-sdk require. It will report that the entry file is missing while really in the background the 'aws-sdk' import is not possible because the nodejs 18 layer uses the aws-sdk v3. 

Above scenario is working as expected when you include the entrypoint file directly in your lambda instead of the layers entry point.

**Comment by mrickard** [comment]
This should be somewhat improved by the Node wrapper changes made in 6bb8023.
