### ISSUE TITLE
NodeJS Agent version out of date

### ISSUE THREAD

**Issue by villelahdenvuo** [newrelic/newrelic-lambda-layers#131]
## Is your feature request related to a problem? Please describe.

Startup check failed: Agent version out of date: v9.7.5, in order access up to date features please upgrade to the latest New Relic node layer that includes agent version v9.8.0

## Feature Description
Use Dependabot or something like that to keep it up to date?

## Priority
Really Want

**Comment by mrickard** [comment]
Closing; agents can be updated by incrementing the layer ARN version to the latest. See https://layers.newrelic-external.com/ for the latest versions.
