### ISSUE TITLE
API Gateway 502 due to Lambda Proxy body is null

### ISSUE THREAD

**Issue by lucasklaassen** [newrelic/newrelic-lambda-layers#141]
I've installed the serverless-newrelic-lambda-layers plugin in my nodejs18.x serverless project ensured i've set the NEW_RELIC_LAMBDA_HANDLER variable for each function and verified that the NR settings are working properly.

I'm running into a problem with API Gateway not receiving the body from my callback when using this integration.

`Endpoint response body before transformations: null`

It appears that statusCode is being passed through properly but for some reason the body parameter is being set to null.

I'm using async lambda handlers and returning like this:

```
  return {

    statusCode: 200,

    body: JSON.stringify({

        responseObj

    })

  };
```

When I remove the newrelic layer plugin and deploy the function it works as expected through the API Gateway lambda proxy set up. It seems like the way the newrelic layer/instrumentation within the newrelic-lambda-wrapper.handler isn't handling the body parameter properly. Is this a known issue? I've spent the past 2 days reading through all of your documentation, going through all of your github repos and searching issues and PRs and I cannot solve this for the life of me.

**Comment by lucasklaassen** [comment]
On further investigation it appears to be related to me using the `async-retry` library.

Running an investigation using a lightweight project and was able to reproduce after I added this in. Will report back with findings.

**Comment by lucasklaassen** [comment]
So even with a successful lambda execution when using the `pg` library, if I make a postgres query like so:

```
const client = new Client(configurations);
await client.connect();
const results = await client.query(text, values);
```

the response breaks between lambda and api gateway for some reason when using the `serverless-newrelic-lambda-layers` plugin.

**Comment by lucasklaassen** [comment]
So here's a lightweight repo which can be used to reproduce this issue: https://github.com/lucasklaassen/newrelic-lambda-layers-bug

After you deploy and hit your lambda through the API endpoint it will return fast and function properly but when you rename your lambda handler to `newrelic-lambda-wrapper.handler` in the AWS console you will experience timeouts and latency issues.

I've tried using the serverless-newrelic-lambda-layers plugin as well as manually instrumenting the lambda function and I either run into timeout/latency errors or I run into a response not returning.

It doesn't seem to be related directly to me using `middyjs` or `pg` it seems to be related to how the `arn:aws:lambda:us-west-2:451483290750:layer:NewRelicNodeJS18X:16` is working.

I've spent the past 3 days debugging this, trying every single combination of deploying using all the documentation you have publicly available and searching through all of github to see how other projects are using this integration.

**Comment by jordigh** [comment]
The service name ends up being used as the New Relic app name.

**Comment by lucasklaassen** [comment]
@jordigh Using this flow I'm not seeing my app show up in the new relic dashboard within the APM section.

I am seeing Span's get logged in the product though, so it is sending data. Any advice on getting this project to show up in entities or apm?

**Comment by lucasklaassen** [comment]
@jordigh I tried the simple example you provided at it worked except for the fact that the app name isn't displaying within the APM, can only see some data through querying spans with NRQL.

However I'm able to recreate the issue when using `middy` and `pg`.

I've updated my example to still be lightweight but showcase the problem: https://github.com/lucasklaassen/newrelic-lambda-layers-bug/blob/main/index.ts

If I remove middy it works as expected AND if I remove pg and leave in middy it works as expected. So it's only when they both are included the api gateway response returns `null` and when I remove the `serverless-newrelic-lambda-layers` plugin, both pg and middy work as expected so it definitely only happens when the layer wraps the method.

```yml
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  profile: personal
  stage: production

functions:
  api:
    handler: index.handler
    environment:
      POSTGRES_USERNAME: ''
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST: ''
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ''
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: 123
    apiKey: ''
```

```javascript
import { Client } from "pg";
const middy = require('middy');

const logging = () => ({
  before: (handler: any, next: Function) => {
    console.log('before', handler);

    return next();
  },
  after: (handler: any, next: Function) => {
    console.log('after', handler);

    return next();
  },
  onError: (handler: any, next: Function) => {
    console.log('onError', handler);

    return next();
  },
});

const main = async (event: any, context: any) => {
  context.callbackWaitsForEmptyEventLoop = false;
  let results;
  const text = `
    SELECT 1
  `
  const values: any[] = [];
  try {
    const configurations: any = {
      user: process.env.POSTGRES_USERNAME,
      host: process.env.POSTGRES_HOST,
      port: process.env.POSTGRES_PORT,
      database: process.env.POSTGRES_DATABASE,
      password: process.env.POSTGRES_PASSWORD,
      connectionTimeoutMillis: 5000,
      idleTimeoutMillis: 30000,
      max: 10,
      ssl: {
        rejectUnauthorized: true,
      },
      allowExitOnIdle: true,
    };
    const client = new Client(configurations);
    await client.connect();
    results = await client.query(text, values);
  } catch(error) {
    console.log('ERROR', error);
  }

  console.log('RESULTS', results);

  return {
    statusCode: 200,
    body: JSON.stringify(
      {
        message: "Go Serverless v3.0! Your function executed successfully!",
        input: event,
      },
      null,
      2
    ),
  };
};

const mainHandler = middy(main)
  .use(logging())

module.exports.handler = mainHandler;
```

**Comment by edwinwong90** [comment]
@lucasklaassen I have the same issue like you. It seem like middy and newrelic-lambda-layers cannot be coexist in the first place. In my case because my middy version is quite old so I decide to latest version, and after upgrade it works now. Hope that help

**Comment by lucasklaassen** [comment]
@edwinwong90 after upgrading middy you've seen no issues?

I remember trying that in the past but I think I may have had too many different configurations going on that attempt.

Are you using the serverless plugin to auto wrap your functions?

**Comment by mrickard** [comment]
@joeythomaschaske I'd recommend opening a support ticket--they can guide you in collecting environment and dependency information (like the version of `aws-serverless-express`...which to the best of my knowledge is an older project that's been succeeded by `serverless-express`.)

**Comment by mrickard** [comment]
@lucasklaassen Our apologies for the long delay in investigating. Thank you for the repro case. This is confirmed to be a conflict with an old version of middy; updating to a recent version resolves it.
