### ISSUE TITLE
Add support for PHP

### ISSUE THREAD

**Issue by fredericgboutin-yapla** [newrelic/newrelic-lambda-layers#146]
## Feature Description
I know, at the moment AWS Lambda does NOT officially support PHP runtime but with the help of [bref.sh](https://github.com/brefphp/bref) one can in fact deploy PHP applications with serverless thus leveraging AWS Lambda functions.

In that situation, we certainly would like to be able to install the [NewRelic PHP Agent](https://github.com/newrelic/newrelic-php-agent) inside the Lambda function, as a layer, so we can monitor our PHP applications.

## Describe Alternatives
The obvious alternative is to use the generic [AWS Lambda monitoring provided by NewRelic](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/monitoring-aws-lambda-serverless-monitoring/) but we miss a ton of info related to PHP execution itself.

Alternatively, I suppose we can try to create our own custom Lambda layer containing the NewRelic PHP Agent. I don't even know if it is possible or if the Agent would work at all in this scenario. TBH I found this very project when I was searching for answers on the matter.

## Additional context
N/A 

## Priority
Probably a "Must Have".

For people already using NewRelic like us and moving to a serverless architecture, we are in a position were we would loose NewRelic for PHP. This is not a blocker but we are definitely not happy with this perspective.

**Comment by fredericgboutin-yapla** [comment]
Oh, it seems there is/was some support for NewRelic - https://github.com/brefphp/bref/pull/34

I'm not sure it works in the new version 2.x or if the Agent is kept up to date but there is definitely something already happening there.

**Comment by mrickard** [comment]
Closing this FR for now--PHP support for Lambda functions doesn't involve this repo.
