### ISSUE TITLE
Java 17 layer

### ISSUE THREAD

**Issue by kerkhofsd** [newrelic/newrelic-lambda-layers#152]
## Is your feature request related to a problem? Please describe.
[AWS Lambda now supports Java 17 as runtime](https://aws.amazon.com/blogs/compute/java-17-runtime-now-available-on-aws-lambda/), however no Java 17 NewRelic layer is available. 

## Feature Description
Provide a NewRelic layer which can be used with the java17 Lambda runtime. 

## Describe Alternatives
/

## Additional context
/

## Priority
Since this might block projects to move to Java 17, I would consider this a "Must Have" or even "Blocker".

**Comment by alycecil** [comment]
looks like #162 was made to solve this but needs to be reviewed

**Comment by gliptak** [comment]
#183 was merged

**Comment by gliptak** [comment]
looking forward to a release to https://layers.newrelic-external.com/

**Comment by gliptak** [comment]
java 17 is available at https://layers.newrelic-external.com/

consider closing

**Comment by jtduffy** [comment]
Thanks for the ping; I forgot to close the issue.
