### ISSUE TITLE
I need Ruby Runtime support

### ISSUE THREAD

**Issue by kaito0228** [newrelic/newrelic-lambda-layers#184]
I heard that the president of New Relic is a Ruby lover.
I often use Ruby because it's easy to write scripts like lambda and it goes well with Ruby.
Please provide Runtime support.

**Comment by jeremiahlukus** [comment]
Great thank you for looking into this, you’re awesome 👍.

**Comment by fallwith** [comment]
Hi @jeremiahlukus. I'm a maintainer for the [New Relic Ruby agent](https://github.com/newrelic/newrelic-ruby-agent). I've developed quite a bit with AWS Lambda myself and would certainly love to help with any initiative that sees New Relic offer ever-improving value to Rubyists.

While we do not currently have any plans to share for Lambda Ruby support, GitHub issues like this one and comments left on it like yours definitely help us gauge interest and build proposals. Thank you for reaching out.

AWS Lambda itself did not originally offer support for Ruby, and New Relic's support for AWS Lambda seems consistent with the language runtimes AWS originally offered. With Ruby support now available from AWS, the Rubyists at New Relic discuss and consider instrumenting it alongside the myriad other priorities being evaluated for other Ruby use cases. And of course in addition to AWS adding support for Ruby, other cloud providers have continually been iterating on their serverless offerings as well and we look at those too.

For the benefit of any observers for this issue, the New Relic Ruby agent offers 2 key alternatives to waiting on official first party support for functionality:

1. Ruby devs can wire up their own [custom instrumentation](https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/ruby-custom-instrumentation/) within their apps
2. All New Relic open source code repositories welcome pull requests

Thanks again for giving the Ruby team some fresh curiosity in this matter that we can surface.

**Comment by chaudharysaket** [comment]
We will release support for Ruby. [PR](https://github.com/newrelic/newrelic-lambda-layers/pull/214) will be merged after testing.

**Comment by chaudharysaket** [comment]
We have [released](https://github.com/newrelic/newrelic-lambda-layers/releases/tag/v9.9.0_ruby) layers for Ruby 3.3 & 3.2 runtimes. Please use [layers website](https://layers.newrelic-external.com/) to get the latest ARN for the Ruby layers. Thanks @fallwith
