### ISSUE TITLE
Java 21 Layer

### ISSUE THREAD

**Issue by SentryMan** [newrelic/newrelic-lambda-layers#188]
## Is your feature request related to a problem? Please describe.

[AWS Lambda now supports Java 21 as a runtime](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-lambda-support-java-21/), however no Java 21 NewRelic layer is available.

## Feature Description
Provide a NewRelic layer which can be used with the java21 Lambda runtime.

## Describe Alternatives
/

## Additional context
/

## Priority
Since this might block projects from moving to Java 21, I would consider this a "Must Have" or even "Blocker".

**Comment by kford-newrelic** [comment]
@SentryMan thanks for alerting us to the AWS update! We're going to try and update our Layers in the next coming quarter
