### ISSUE TITLE
Node lambda layer tries to access SSM for license key

### ISSUE THREAD

**Issue by Marcholio** [newrelic/newrelic-lambda-layers#203]
## Description

We have configured NodeJS lambdas with newrelic layer. We are using layer version `arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicNodeJS20XARM64:4`. From CloudTrail events we can see that the layer tries to access SSM parameter NEW_RELIC_LICENSE_KEY, which fails because there's no such parameter and the lambda is not authorized to perform SSM requests. We are storing the license key in Secrets manager as instructed in the [docs](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/) and it's working as expected.

SSM request in that case is unnecessary and undocumented, so it should be removed. Unnecessary requests consume the SSM quota, which is [very limited by default](https://docs.aws.amazon.com/general/latest/gr/ssm.html), so extra requests should be avoided.

## Steps to Reproduce

1. Setup nodejs lambda with the layer
2. Store License key in secrets manager as instructed
3. Enable CloudTrail logs
4. Invoke lambda
5. Investigate CloudTrail logs and see that there's a failed request to SSM GetParameter.

## Expected Behaviour

No unnecessary calls to SSM parameter store.

## Relevant Logs / Console output

Successful secrets manager request:
```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "***",
        "arn": "arn:aws:sts::***",
        "accountId": "***",
        "accessKeyId": "***",
        "sessionContext": {***}
    },
    "eventTime": "2024-02-02T08:47:59Z",
    "eventSource": "secretsmanager.amazonaws.com",
    "eventName": "GetSecretValue",
    "awsRegion": "eu-west-1",
    "sourceIPAddress": "***",
    "userAgent": "aws-sdk-go/1.44.288 (go1.19.11; linux; arm64)",
    "requestParameters": {
        "secretId": "NEW_RELIC_LICENSE_KEY"
    },
    "responseElements": null,
    "requestID": "***",
    "eventID": "***",
    "readOnly": true,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "***",
    "vpcEndpointId": "***",
    "eventCategory": "Management"
}
```

Denied SSM request:
```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "***",
        "arn": "arn:aws:sts::***",
        "accountId": "***",
        "accessKeyId": "***",
        "sessionContext": {***}
    },
    "eventTime": "2024-02-02T08:47:59Z",
    "eventSource": "ssm.amazonaws.com",
    "eventName": "GetParameter",
    "awsRegion": "eu-west-1",
    "sourceIPAddress": "***",
    "userAgent": "aws-sdk-go/1.44.288 (go1.19.11; linux; arm64)",
    "errorCode": "AccessDenied",
    "errorMessage": "User: arn:aws:sts::*** is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-west-1:***:parameter/NEW_RELIC_LICENSE_KEY because no identity-based policy allows the ssm:GetParameter action",
    "requestParameters": null,
    "responseElements": null,
    "requestID": "***",
    "eventID": "***",
    "readOnly": true,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "***",
    "eventCategory": "Management"
}
```

## Your Environment

NodeJS v20 Lambda with layer `arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicNodeJS20XARM64:4`.

**Comment by iamemilio** [comment]
Please see: https://github.com/newrelic/newrelic-lambda-extension/issues/191
