### ISSUE TITLE
Missing entity name for lambda logs

### ISSUE THREAD

**Issue by alankritjoshi** [newrelic/newrelic-lambda-layers#257]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

I don't see the logs associated with any entities so I can't create workloads to specify them or namespace the events or metrics.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

- Use new relic lambda layer
- Observe logs

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

- If a newrelic.ini feel or env var for `NEW_RELIC_APP_NAME` is provided, it should use it for entity name?

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

e.g.,

```
{
  "aws.lambda_request_id": "b39b3a-c0d1-4e49-8-9a4b5fba80",
  "faas.arn": "arn:aws:lambda:us-east-1:*:function:*-personal-acquisition-job-trigger-lambda-4fb569f",
  "faas.execution": "b3979-c0d1-4e49-88-9a4b5fba80",
  "faas.name": "personal-acquisition-job-trigger-lambda-4fb569f",
  "level": "INFO",
  "logger": "root",
  "message": "Received SNS message: 5566f-1e78-5acd-869e-5ed548",
  "newrelic.source": "api.logs",
  "plugin": "newrelic-lambda-extension:2.3.12",
  "requestId": "b39b3a-c0d1-4e49-8-9a4b5fba80",
  "timestamp": 1719716305000,
  "trace.id": ""
}
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

Chrome, MacOS

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by chaudharysaket** [comment]
Hi @alankritjoshi 
The instrumented lambda can forward the logs to New Relic either via Extension or log-ingestion subscription. 

- To use Extension: 
     - set  `NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS` environment variable to `true`

- To use [log-ingestion](https://github.com/newrelic/aws-log-ingestion/issues) subscription filter:
    - use [CLI command](https://github.com/newrelic/newrelic-lambda-cli?tab=readme-ov-file#newRelic-log-subscription) to enable subscription filter for the lambda.

Thank you

**Comment by alankritjoshi** [comment]
I'm using the extension and I've the env var set to true. So I'm able to see the logs in the global view.

My question is how do I ensure that the logs are tied to an Entity? If an entity is associated, it would help me create a workload for these logs.

**Comment by alankritjoshi** [comment]
Additionally, related question, how do I scope down the events and metrics that I create with this layer and extension? Right now those show up in global scope too.
