### ISSUE TITLE
newrelic-lambda-layers-nodejs do not support arm64

### ISSUE THREAD

**Issue by i-am-ian** [newrelic/newrelic-lambda-layers#274]
## Description

The published images do not support ARM64, even when explicitly indicated via the tag. On Apple Silicon, running a container that includes the New Relic lambda extension from these layers results in errors.

## Steps to Reproduce

Note: inspecting `:20-arm64` and `:20` yield similar results.
```
docker manifest inspect public.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-nodejs:20-arm64 -v
{
        "Ref": "public.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-nodejs:20-arm64",
        "Descriptor": {
                "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                "digest": "sha256:d338aad480fc906d2bf6f5884ae08b87ee11898166de6aa80cdb261a4529df5a",
                "size": 1370,
                "platform": {
                        "architecture": "amd64",
                        "os": "linux"
                }
        },
        ...
}
```

## Expected Behaviour

Inspecting the manifest should show arm64 as an available architecture. It would be great if the image with the `:20` tag supported both arm64 and amd64.

For reference, here is the result of inspecting the 20-arm64 nodejs lamba image:
```
docker manifest inspect public.ecr.aws/lambda/nodejs:20-arm64 -v
{
        "Ref": "public.ecr.aws/lambda/nodejs:20-arm64",
        "Descriptor": {
                "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                "digest": "sha256:79892c2050c0843cdf6a2807b5717bf8dbadeebd050405ef8c4923c93c8db567",
                "size": 1580,
                "platform": {
                        "architecture": "arm64",
                        "os": "linux",
                        "variant": "v8"
                }
        },
        ...
}
```
and the multi-architecture nodejs lambda image:
```
docker manifest inspect public.ecr.aws/lambda/nodejs:20
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1580,
         "digest": "sha256:dd6bac959b9e8b7624daa2b153ef4543fa6175ad9d3eadef67bfa3e4e435520a",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1580,
         "digest": "sha256:5934300252bd4bed25eb4d676bbd4d5ae30fd9d5faa71082587b47609af667d4",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by chaudharysaket** [comment]
> It would be great if the image with the :20 tag supported both arm64 and amd64.

Since New Relic lambda layer consists of 
1. [Extension](https://github.com/newrelic/newrelic-lambda-extension), which is architecture [`arm` & `amd`] dependent, & 
2. New Relic language agent, [Node agent](https://github.com/newrelic/node-newrelic) in this case,

We cannot use the `:20` image tag to support both `arm` and `amd` architectures. 
I will look into the why running a container on Apple Silicon with layers `newrelic-lambda-layers-nodejs:20-arm64`  is resulting in errors.

**Comment by chaudharysaket** [comment]
Thank you @i-am-ian for bringing the issue to our attention. I have created a [PR](https://github.com/newrelic/newrelic-lambda-layers/pull/275), after review we will release images for `arm` architecture to resolve the issue.

**Comment by chaudharysaket** [comment]
We have published new ecr images which resolves this issue. Now, if we execute 
`docker manifest inspect public.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-nodejs:20-arm64 -v`

We can see `arm64` in the descriptor 
```
{
	"Ref": "public.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-nodejs:20-arm64",
	"Descriptor": {
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"digest": "sha256:d29daec7a49d86a28daa05b4dcdb31f4911db595852dcb5707b2be73408227f8",
		"size": 1370,
		"platform": {
			"architecture": "arm64",
			"os": "linux"
		}
	},
```
