### ISSUE TITLE
Timeouts with arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS20X:39

### ISSUE THREAD

**Issue by Shereef** [newrelic/newrelic-lambda-layers#277]
## Description

We have a lambda with very high invocation count
usually takes a few milliseconds to respond
it randomly started timing out even when sending bad requests which usually responds instantly
we put logs and they never went to NR and when that happens the only thing it cloud watch is:
```
[NR_EXT] New Relic Lambda Extension starting up
[NR_EXT] Initializing version 2.3.13 of the New Relic Lambda Extension...
[NR_EXT] Failed to retrieve New Relic license key No license key configured
[NR_EXT] Starting no-op mode, no telemetry will be sent
EXTENSION	Name: newrelic-lambda-extension	State: Ready	Events: [INVOKE, SHUTDOWN]
INIT_REPORT Init Duration: 10001.07 ms	Phase: invoke	Status: timeout
START RequestId: ece31e2b-441d-4e9d-924b-3efbd222164b Version: $LATEST
END RequestId: ece31e2b-441d-4e9d-924b-3efbd222164b
REPORT RequestId: ece31e2b-441d-4e9d-924b-3efbd222164b	Duration: 10000.00 ms	Billed Duration: 10000 ms	Memory Size: 128 MB	Max Memory Used: 111 MB	Status: timeout
```

## Steps to Reproduce

1. use `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS20X:39`
2. call the lambda 3000 thousand times in the course of 3 minutes
3. watch it timeout

## Expected Behaviour

it would not timeout

## Relevant Logs / Console output

```
[NR_EXT] New Relic Lambda Extension starting up
[NR_EXT] Initializing version 2.3.13 of the New Relic Lambda Extension...
[NR_EXT] Failed to retrieve New Relic license key No license key configured
[NR_EXT] Starting no-op mode, no telemetry will be sent
EXTENSION	Name: newrelic-lambda-extension	State: Ready	Events: [INVOKE, SHUTDOWN]
INIT_REPORT Init Duration: 10001.07 ms	Phase: invoke	Status: timeout
START RequestId: ece31e2b-441d-4e9d-924b-3efbd222164b Version: $LATEST
END RequestId: ece31e2b-441d-4e9d-924b-3efbd222164b
REPORT RequestId: ece31e2b-441d-4e9d-924b-3efbd222164b	Duration: 10000.00 ms	Billed Duration: 10000 ms	Memory Size: 128 MB	Max Memory Used: 111 MB	Status: timeout
```

## Your Environment

aws lambda using nodejs 20
timeout is 10 seconds on dev and it was timing out

## Additional context

For the time being I went to aws console and changed the layer version to 38 and it is working fine with 90000 invocations so far
`arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS20X:38` is fine

**Comment by aavinash-nr** [comment]
Hello @Shereef , We've investigated the bug and attempted to reproduce it using the same configuration, but unfortunately, we were unable to replicate the issue. We've tried invoking the `us-east-1:451483290750:layer:NewRelicNodeJS20X:39` version with 3,000 and 9,000 invocations for 3 minutes. Could you please share the environment variables being used in your setup? Additionally, it would be helpful if you could provide some sample code to aid our troubleshooting process.
