### ISSUE TITLE
Upgrade jackson-databind:2.12.2

### ISSUE THREAD

**Issue by kanderson250** [newrelic/newrelic-lambda-layers#282]
The current jackson-databind dependency has some CVEs. Upgrade to a stable version per this [GTSE](https://new-relic.atlassian.net/browse/NR-337949).

**Comment by deleonenriqueta** [comment]
The GTSE was referencing an outdated version of the Lambda Layer `v2.2.1.13_java`. The latest version `v2.4.1_java` includes an updated version of the **jackson-bind** library that resolves those reported vulnerabilities. The recommendation  for the customer is to upgrade to the latest version of the Lambda Layer.
