### ISSUE TITLE
feat: Support Node 22 as a Lambda runtime

### ISSUE THREAD

**Issue by mrickard** [newrelic/newrelic-lambda-layers#296]
## Is your feature request related to a problem? Please describe.
Now that Node 22 has been announced as a supported Lambda runtime, we should publish Node 22 layers.

## Additional context
I'll take this; I'm filing an issue here to track the work. 

## Priority
Soon enough this will be a Must-Have for customers.

**Comment by chaudharysaket** [comment]
[PR](https://github.com/newrelic/newrelic-lambda-layers/pull/297) merged. Lambda layers for Nodejs.22 will be released shortly

**Comment by chaudharysaket** [comment]
[Released](https://github.com/newrelic/newrelic-lambda-layers/releases/tag/v12.8.0.1_nodejs) Lambda layers and ECR images for Nodejs 22. 
Please use [lambda-layers website](https://layers.newrelic-external.com/) to find out the latest layer `arn` as per the `region`. 
ECR Images for Nodejs 22 can be found [here](https://gallery.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-nodejs)
