### ISSUE TITLE
Release layer with node-sdk 12.8.2

### ISSUE THREAD

**Issue by Engerim** [newrelic/newrelic-lambda-layers#300]
## Description

The node sdk 12.8.1 contains a bug where the sdk tries to set a web request when an event lambda payload contains the `resource` key. That is fixed in 12.8.2 with that pr https://github.com/newrelic/node-newrelic/pull/2825. As the layer atm contains only 12.8.1 the wrong behaviour is still there present

**Comment by Engerim** [comment]
@mrickard @chaudharysaket can you pls have a looks thx

**Comment by mrickard** [comment]
@Engerim Thank you for bringing this to our attention. @chaudharysaket published the latest version, so that should be available now.
