### ISSUE TITLE
Adding permissions so layers can be publicly listed

### ISSUE THREAD

**Issue by stdlibdoh** [newrelic/newrelic-lambda-layers#41]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

Trying to perform any action that requires a `ListLayerVersions` API call returns a permissions error to do with a missing `lambda:listLayerVersions` policy.

This would be useful as it would allow fetching the latest layer.

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

The `ListLayerVersions` operations should return New Relic's Lambda Layers information

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

Adding the following policy to each layer should achieve this result:

```
Type: AWS::Lambda::LayerVersionPermission
Properties: 
  Action: lambda:listLayerVersions
  LayerVersionArn: !Ref LayerVersionArn
  Principal: *

```

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

Apologies if this doesn't belong in this repository, more than happy to recreate it where it belongs.

We primarily use Terraform for infrastructure-as-code and, for APM instrumentation, we keep the layer ARN stored in SSM. This means that, every once in awhile, someone has to go and verify that lambda layer versions are up to date, and update them if they're not.

If the layers had this policy attached, this would simply be a matter of fetching the latest layer version in Terraform, via a data block reference, similarly to the functionality that exists when using the Serverless Framework plugin.

**Comment by kolanos** [comment]
@stdlibdoh Thanks for this feature request. We actually have an API for retrieving the latest layer version. This API powers [this site](https://layers.newrelic-external.com), but you can use it directly:

```bash
curl https://<region>.layers.newrelic-external.com/get-layers?CompatibleRuntime=<runtime>
```

For example:

```bash
curl https://us-east-1.layers.newrelic-external.com/get-layers?CompatibleRuntime=python3.8
```

There's also a `CompatibleArchitecture` parameter, but it only works in regions that currently support ARM64 Lambdas.

Hope that helps.
