### ISSUE TITLE
Using the layer without redirecting the handler

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [newrelic/newrelic-lambda-layers#53]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
I am currently investigating different ways to integrate New Relic into our Node lambdas and I am very interested in using your layers. However the only documented method for using them involves redirecting the handler to the layer via the settings. We are already doing this with another layer integration and it looks like chaining layers (having one layer redirect to anothe) is not supported (at least it does not work). So my question is, is there another way to use the layer? Otherwise we are left with only the legacy integration.
[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour
It would be nice If I could still use the layer without having the redirect the handler.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution
I have not spent a ton of time researching if this is possible, but it looks like layers can be imported in node just like any other library. Would it be possible to use it similar to how the newrelic npm library is used?
```javascript
const newrelicLayer = require('layer');
module.exports.handler = newrelicLayer.setLambdaHandler((event, context, callback) => {
...
});
```

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
We are already redirecting the handler to another layer integration and cannot change that.

**Comment by mrickard** [comment]
@rmclaughlin-nelnet I think you could do this already by doing something like your proposed solution. In the case of Node, you could indeed reference the layer as if it was a dependency that'd been included in your deployment. You should be able to have 

`const newrelic = require('newrelic')`

at the top of your handler file, and then wrap the handler the way you're showing.

**Comment by rmclaughlin-nelnet** [comment]
Your right, this does seem to work. Thanks for pointing out that it can already be done. It would be great to get this added to the documentation.

**Comment by kolanos** [comment]
@rmclaughlin-nelnet We'll look into a better way to perform this handler check for this kind of setup. We'll also consider documeting this setup, however we already have more approaches documented than we'd like, so we're hoping to simplify the setup process where possible. Glad to hear you got it working, though.
