### ISSUE TITLE
NEW_RELIC_LOG_LEVEL environment variable missing

### ISSUE THREAD

**Issue by kamaz** [newrelic/newrelic-lambda-layers#6]
## Description

We have tried to use NewRelic layer version 6 for Node 12 with log level configured to `debug` but that configuration does not seem to work. When you downgrade to version 4 of published layer all works as expected.

## Steps to Reproduce

Configure layer to `arn:aws:lambda:eu-central-1:451483290750:layer:NewRelicNodeJS12X:6`
Configure lambda environment variable to `NEW_RELIC_LOG_LEVEL: trace`
Navigate to cloudwatch logs no trace output.

Same applies to `debug`

## Expected Behaviour

Trace / Debug log present in cloudwatch logs

## Relevant Logs / Console output

N/A

## Your Environment

N/A

## Additional context

N/A

**Comment by mrickard** [comment]
Closing; issue resolved with https://github.com/iopipe/serverless-newrelic-lambda-layers/pull/41
