### ISSUE TITLE
commit 63855c2 causes java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/newrelic-lambda-layers#62]
## Description

The lambda will immediately fail after invocation.

Commit 63855c2 is part of #46.

[This file has not been changed since Apr 23rd before that.](https://github.com/newrelic/newrelic-lambda-layers/commits/master/java/src/main/java/com/newrelic/java/JavaClassLoader.java)

## Steps to Reproduce

The bug only occurs in the latest version 8 of the Java11 layer.
After downgrading to the lambda version 7 everything worked fine again.

## Expected Behaviour

Lambda version 8 of the Java11 layer should not produce this error and should not cause invocations to fail.

## Relevant Logs / Console output

```log
Error loading class com.newrelic.java.HandlerWrapper: io/opentracing/Tracer: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: io/opentracing/Tracer
```

## Your Environment

- Runtime: Java 11 (Corretto)
- Framework: Quarkus
- javaNewRelicHandler: handleStreamsRequest
- layer: arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicJava11:8

**Comment by kolanos** [comment]
Fixed in #63.
