### ISSUE TITLE
Canada (Central) region missing latest version of layers

### ISSUE THREAD

**Issue by youngbob** [newrelic/newrelic-lambda-layers#68]
## Description

I am deploying an AWS Lambda function on Node 14 to multiple AWS regions. I got the latest layer version from https://layers.newrelic-external.com/, and used the same version for all regions I was deploying in. However, deploying to the ca-central-1 region failed because it is a few builds behind on the Node 14 layer. Viewing the region on the layers site and comparing to other regions looks like several other layers are missing completely (no ARM64 layers) or out of date like Node 14.

## Steps to Reproduce

Deploy a Lambda function with a layer of (terraform): `"arn:aws:lambda:${data.aws_region.current.name}:451483290750:layer:NewRelicNodeJS14X:33"`

This succeeds in multiple regions but fails in ca-central-1 because the latest version available is 31, not 33.

## Expected Behaviour

The same layers should be available in all regions.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

* AWS Lambda
* Node 14
* Terraform
* 5 global AWS regions

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by mrickard** [comment]
@youngbob Thank you for the report! Yes, ARM64 isn't yet available in ca-central-1. 

As for the layer version numbers, those aren't going to be in sync across regions. Layers are published as new agents are released, and AWS increments the version number with each published layer. What this means is that newer regions (ca-central-1, eu-north-1, eu-south-1, etc.) are going to have layer version numbers that are out of sync with older regions (us-west-1, us-east-1...). I'd recommend querying the API on a per-region basis, rather than relying on version number consistency across regions.

**Comment by youngbob** [comment]
@mrickard Thanks for explaining. Can you give any more details on how I should be querying an API for each region or any other suggestion on how I can always get the latest version of the layer? Examples like https://github.com/newrelic/newrelic-lambda-extension/tree/main/examples/terraform/nodejs seem to just hardcode the ARN for a specific region, and the example ARNs get updated manually like in https://github.com/newrelic/newrelic-lambda-extension/pull/73

**Comment by mrickard** [comment]
@youngbob To get all layers for a region, you'd GET from https://ca-central-1.layers.newrelic-external.com/get-layers. To limit to a particular runtime like Node 14, you'd GET https://ca-central-1.layers.newrelic-external.com/get-layers?CompatibleRuntime=nodejs14.x.

**Comment by mrickard** [comment]
@yannick-fernand We've made a ticket for this; I'll update when the layers are published.

**Comment by mrickard** [comment]
@yannick-fernand @youngbob Graviton2 layers are now available in Canada (central). Currently for Node, but anticipate layers for Python coming in a day or so.
