### ISSUE TITLE
Compatibility with aws-cdk aws-lambda-nodejs

### ISSUE THREAD

**Issue by okko** [newrelic/newrelic-lambda-layers#79]
## Summary

The AWS CDK NodejsFunction construct creates a Lambda function with automatic transpiling and bundling of TypeScript or Javascript code. https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html

It has a hardcoded handler parameter in the format of "index.{handler}", https://github.com/aws/aws-cdk/blob/5c40b90707b869f62e59613d50d5deaafbaa52f1/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L114

This is incompatible with New Relic's Lambda Layer requiring to set the handler to "newrelic-lambda-wrapper".

## Desired Behaviour

New Relic Lambda Layer compatible with NodejsFunction, with code like

```
const func = new NodejsFunction(this, 'myFunction', {
        handler: 'newrelic-lambda-wrapper.handler',
      });
func.addLayers(newRelicLayer);
func.addEnvironment('NEW_RELIC_ACCOUNT_ID', newRelicAccountId);
func.addEnvironment('NEW_RELIC_LAMBDA_HANDLER', 'handler');
```

## Possible Solution A

Provide the `newrelic-lambda-wrapper` also as `index.newrelic-lambda-wrapper` for compatibility.
https://github.com/newrelic/newrelic-lambda-layers/blob/039ec8e7550e7f18ddf3efae8b3feee1c839327e/nodejs/publish-layers.sh#L74

Easy to use.

## Possible Solution B

Ask AWS to make the "index." part overrideable or configurable, and add documentation for that in the New Relic documentation.

**Comment by okko** [comment]
I also tried the format

```
const func = new NodejsFunction(this, 'myFunction', {
        entry: 'newrelic-lambda-wrapper',
        handler: 'handler',
      });
func.addLayers(newRelicLayer);
func.addEnvironment('NEW_RELIC_ACCOUNT_ID', newRelicAccountId);
func.addEnvironment('NEW_RELIC_LAMBDA_HANDLER', 'index.handler');
```

but then aws-lambda-nodejs throws "Error: Only JavaScript or TypeScript entry files are supported."

**Comment by a-w-l** [comment]
See https://github.com/aws/aws-cdk/issues/16795 for a workaround

**Comment by chaudharysaket** [comment]
Seems like [cdk v2](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html) solves this issue.
The sample code provided in the docs, states how to provide wrapper script.
```
new nodejs.NodejsFunction(this, 'MyFunction', {
  entry: '/path/to/my/file.ts', // accepts .js, .jsx, .cjs, .mjs, .ts, .tsx, .cts and .mts files
  handler: 'myExportedFunc', // defaults to 'handler'
});
```
In the above code, we can set handler to `newrelic-lambda-wrapper.handler`. This will invoke the New Relic wrapper script.
