### ISSUE TITLE
Support Node.js ES Modules

### ISSUE THREAD

**Issue by tarantoj-intrepid** [newrelic/newrelic-lambda-layers#83]
## Summary
AWS Lambda now supports ES module handlers on Node runtimes >= 14. However, the new relic layer utilises `require` to execute the handler it is wrapping, `require` cannot import ES modules.

## Desired Behaviour
The layer is able to import `.mjs` handlers

## Possible Solution
Try to use a dynamic import statement if `getHandler` fails when using `require`

## Additional context
https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/

**Comment by mrickard** [comment]
@tarantoj-intrepid This was something we investigated, and unfortunately there's a fundamental blocker: `NODE_PATH` is not used in resolving `import` specifiers. See [the Node ESM docs](https://nodejs.org/api/esm.html#no-node_path) for this. 

The no-code-change instrumentation we have leverages AWS's layers standard for installing our agent in `/opt/nodejs` while being able to instrument dependencies in `/var/task`, finding them by using `NODE_PATH`. Without an ambient path available, the agent in `/opt/nodejs` can't find your dependencies or handler. 

While that rules out using the Lambda Layer, you can still instrument ESM Lambda functions with New Relic, by following [these instructions](https://github.com/newrelic/newrelic-lambda-layers#support-for-es-modules-nodejs).
