### ISSUE TITLE
[Python] Handlers inside a PEP 420  namespaces aren't working

### ISSUE THREAD

**Issue by Gaasmann** [newrelic/newrelic-lambda-layers#90]
# Handlers inside a PEP 420  namespaces aren't working

## Description

When a lambda using this layer tries to load the handler that comes from a module included in a namespace, the import fails.
For example, if your handler is under "namespace.package.handler", an exception will be returned saying that "namespace" isn't a package.

The issue is most likely coming from https://github.com/newrelic/newrelic-lambda-layers/blob/df3459626e17fd4843607a66e272c494e36b8f36/python/newrelic_lambda_wrapper.py#L61 as the modules are found and loaded using the "imp" module, which is deprecated since Python 3.4. 

The module "importlib" should be used instead. That would most likely solve this issue + avoid the for loop "imp" requires to load sub-modules.

## Steps to Reproduce

Define a handler that is inside a namespace (e.g. NEW_RELIC_LAMBDA_HANDLER=namespace.package.handler)
Run the lambda function.

## Expected Behaviour

The NR layer should be able to import the handler and run the lambda.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

Python3.9 (AWS Python runtime)

**Comment by kolanos** [comment]
@Gaasmann Are you putting `__init__.py` files in each of your modules/submodules? We would welcome a pull request updating imp to importlib.
